### ISSUE TITLE
代码实现效果咨询

### ISSUE THREAD

**Issue by JiaDS1** [laiyao1/OpenSMax#1]
您好，看了您的代码和论文我觉得倍受启发，所以此前我调通了您的开源项目：OpenSMax，代码中默认是选的symmi一种作为未知类，我得到的效果和论文中差不多。
但是在尝试修改代码中将比例调整到20%~50%的过程中，“SVM2”的效果达不到论文中的效果，只有70%左右，也不知道是不是我代码改的有问题。
  如果您方便的话，我想知道在改变未知类比例时代码应该修改哪些地方。或者想看看您是否有改好的代码可以参考

**Comment by laiyao1** [comment]
你好，感谢你对我们工作的关注。

这个工作是我读硕士研究生期间的工作，现在我已经毕业3年多并且换了方向，现在已经很难找到原实验的设置。但是你可以尝试调整未知类的具体类别，因为DGA类别虽然互相之间是独立的，但也存在着相似关系，尝试变换25%~50%未知类中具体用了哪些类别或许结果会有不同。
